name:                go-notebook-language-server
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- lsp-types >= 2.0.0.1
- monad-logger
- string-interpolate
- text
- unliftio

default-extensions:
- OverloadedStrings
- QuasiQuotes
- NamedFieldPuns
- RecordWildCards
- ScopedTypeVariables
- FlexibleContexts
- FlexibleInstances
- LambdaCase
- ViewPatterns
- MultiWayIf
- TupleSections
- NumericUnderscores
- TypeApplications

ghc-options:
- -Wunused-packages
- -Wall
- -fno-warn-name-shadowing

library:
  source-dirs: src
  dependencies:
  - aeson
  - auto-update
  - bytestring
  - containers
  - filepath
  - lens
  - lens-regex-pcre
  - mtl
  - myers-diff
  - network-uri
  - pcre-light
  - random
  - safe
  - text-rope
  - time
  - unliftio-core
  - uuid
  - vector

executables:
  go-notebook-language-server:
    main: Main.hs
    source-dirs:
    - app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -W
    dependencies:
    - aeson
    - attoparsec
    - bytestring
    - lens
    - mtl
    - optparse-applicative
    - process
    - retry
    - go-notebook-language-server
    - unix
    - unliftio-core

tests:
  go-notebook-language-server-test:
    main: Main.hs
    source-dirs:
    - test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -W
    dependencies:
    - QuickCheck
    - containers
    - go-notebook-language-server
    - directory
    - exceptions
    - filepath
    - lens
    - lsp-test
    - lsp-test-helpers
    - lsp-types
    - monad-logger
    - mtl
    - myers-diff
    - quickcheck-instances
    - sandwich
    - sandwich-contexts
    - string-interpolate
    - temporary
    - text-rope
    - unliftio
    - unliftio-core
    - vector
