resolver: nightly-2025-11-19

packages:
- .

nix:
  enable: false

system-ghc: true

extra-deps:
- git: https://github.com/codedownio/sandwich
  # long-running-nodes branch
  commit: c3e16ccda384917fba1ccc5f3cf8f592415562c1
  subdirs:
  - sandwich
  - sandwich-contexts
  - sandwich-quickcheck

- git: https://github.com/codedownio/lsp.git
  # upgrade-monads-newest-jan2026 branch
  commit: d920b28aa25d454812d8d9bbd922e893574d45bc
  subdirs:
  - lsp
  - lsp-test
  - lsp-types

- git: https://github.com/codedownio/lsp-test-helpers.git
  # main branch
  commit: 98ed0dde02e9e784b4ab73f2d5330ee0a9a0b1e4
