resolver: nightly-2025-11-19

packages:
- .

nix:
  enable: false

system-ghc: true

extra-deps:
- git: https://github.com/codedownio/sandwich
  # long-running-nodes branch
  commit: c3e16ccda384917fba1ccc5f3cf8f592415562c1
  subdirs:
  - sandwich
  - sandwich-contexts
  - sandwich-quickcheck

- git: https://github.com/codedownio/lsp.git
  # upgrade-monads-newest-jan2026 branch
  commit: c723f4a4fb99661c76b1356f8a839a0e266b0f32
  subdirs:
  - lsp
  - lsp-test
  - lsp-types

- git: https://github.com/codedownio/lsp-test-helpers.git
  # main branch
  commit: 3aead859c272db11879cec58bef0f4e65244be45
